#ifndef WEB_UI_H
#define WEB_UI_H

const char web_ui_html[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Station Pico</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#eee;display:flex;flex-direction:column;height:100vh}"
"header{background:#16213e;padding:10px 20px;display:flex;align-items:center;gap:15px;border-bottom:2px solid #0f3460}"
"header h1{font-size:18px;color:#e94560}"
"#status{font-size:12px;color:#0f0}"
".main{display:flex;flex:1;overflow:hidden}"
".canvas-wrap{flex:1;display:flex;align-items:center;justify-content:center;background:#0a0a1a;padding:10px}"
"#preview{border:2px solid #333;image-rendering:pixelated;max-width:100%;max-height:100%}"
".tools{width:260px;background:#16213e;padding:15px;overflow-y:auto;border-left:2px solid #0f3460}"
".tools h3{color:#e94560;margin:10px 0 5px;font-size:13px}"
".tools select,.tools input,.tools button{width:100%;padding:6px 8px;margin:3px 0;border:1px solid #333;"
"border-radius:4px;background:#1a1a2e;color:#eee;font-size:13px}"
".tools button{background:#e94560;border:none;cursor:pointer;font-weight:bold}"
".tools button:hover{background:#c73e54}"
".row{display:flex;gap:5px}"
".row>*{flex:1}"
".colors{display:flex;flex-wrap:wrap;gap:4px;margin:5px 0}"
".colors div{width:28px;height:28px;border-radius:4px;cursor:pointer;border:2px solid transparent}"
".colors div.active{border-color:#fff}"
".info{font-size:11px;color:#888;margin-top:10px;padding-top:10px;border-top:1px solid #333}"
"</style></head><body>"
"<header><h1>STATION PICO</h1><span id='status'>Connecting...</span></header>"
"<div class='main'>"
"<div class='canvas-wrap'><canvas id='preview' width='640' height='480'></canvas></div>"
"<div class='tools'>"
"<h3>Draw</h3>"
"<select id='tool'><option value='rect'>Rectangle</option><option value='circle'>Circle</option>"
"<option value='line'>Line</option><option value='text'>Text</option>"
"<option value='pixel'>Pixel</option></select>"
"<input id='textInput' placeholder='Text (for text tool)' style='display:none'>"
"<div class='row'><input id='sizeInput' type='number' value='20' min='1' max='100' placeholder='Size'>"
"<select id='fillSel'><option value='0'>Outline</option><option value='1'>Filled</option></select></div>"
"<h3>Color</h3>"
"<div class='colors' id='fgColors'></div>"
"<h3>Background</h3>"
"<div class='colors' id='bgColors'></div>"
"<h3>Font Size</h3>"
"<select id='fontSel'><option value='8'>Small (8px)</option><option value='12'>Medium (12px)</option>"
"<option value='16' selected>Regular (16px)</option><option value='20'>Large (20px)</option>"
"<option value='24'>XLarge (24px)</option></select>"
"<h3>Actions</h3>"
"<button onclick='sendClear()'>Clear Canvas</button>"
"<button onclick='sendDraw()' style='margin-top:5px;background:#0f3460'>Send to Display</button>"
"<button onclick='location.reload()' style='margin-top:5px;background:#333'>Refresh Status</button>"
"<div class='info' id='info'>Loading...</div>"
"</div></div>"
"<script>"
"const COLORS=[{n:'BLACK',v:0,c:'#000'},{n:'BLUE',v:1,c:'#0000cc'},{n:'GREEN',v:2,c:'#00cc00'},"
"{n:'CYAN',v:3,c:'#00cccc'},{n:'RED',v:4,c:'#cc0000'},{n:'MAGENTA',v:5,c:'#cc00cc'},"
"{n:'YELLOW',v:6,c:'#cccc00'},{n:'WHITE',v:7,c:'#fff'}];"
"let fg=7,bg=0;"
"const cv=document.getElementById('preview'),ctx=cv.getContext('2d');"
"const dColors=['#000','#0000cc','#00cc00','#00cccc','#cc0000','#cc00cc','#cccc00','#fff'];"
"function mkColors(id,sel,cb){const el=document.getElementById(id);"
"COLORS.forEach(c=>{const d=document.createElement('div');d.style.background=c.c;"
"d.title=c.n;if(c.v===sel)d.classList.add('active');"
"d.onclick=()=>{el.querySelectorAll('div').forEach(x=>x.classList.remove('active'));"
"d.classList.add('active');cb(c.v)};el.appendChild(d)})}"
"mkColors('fgColors',fg,v=>{fg=v});mkColors('bgColors',bg,v=>{bg=v});"
"document.getElementById('tool').onchange=e=>{"
"document.getElementById('textInput').style.display=e.target.value==='text'?'block':'none'};"
"let drawing=false,startX=0,startY=0;"
"cv.onmousedown=e=>{const r=cv.getBoundingClientRect();"
"startX=Math.round((e.clientX-r.left)*640/r.width);startY=Math.round((e.clientY-r.top)*480/r.height);drawing=true};"
"cv.onmouseup=e=>{if(!drawing)return;drawing=false;"
"const r=cv.getBoundingClientRect();"
"const endX=Math.round((e.clientX-r.left)*640/r.width),endY=Math.round((e.clientY-r.top)*480/r.height);"
"previewDraw(startX,startY,endX,endY)};"
"function previewDraw(x1,y1,x2,y2){const t=document.getElementById('tool').value;"
"ctx.fillStyle=dColors[fg];ctx.strokeStyle=dColors[fg];"
"if(t==='rect'){const f=document.getElementById('fillSel').value==='1';"
"f?ctx.fillRect(x1,y1,x2-x1,y2-y1):ctx.strokeRect(x1,y1,x2-x1,y2-y1)}"
"else if(t==='circle'){const r=Math.round(Math.sqrt((x2-x1)**2+(y2-y1)**2));"
"ctx.beginPath();ctx.arc(x1,y1,r,0,Math.PI*2);"
"document.getElementById('fillSel').value==='1'?ctx.fill():ctx.stroke()}"
"else if(t==='line'){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}"
"else if(t==='text'){const txt=document.getElementById('textInput').value||'Hello';"
"const sz=document.getElementById('fontSel').value;ctx.font=sz+'px monospace';"
"ctx.fillStyle=dColors[fg];ctx.fillText(txt,x1,y1+parseInt(sz))}"
"else if(t==='pixel'){ctx.fillRect(x1,y1,2,2)}}"
"function api(path){return fetch('/api/'+path).then(r=>r.json())}"
"function sendClear(){api('clear?color='+bg).then(()=>{ctx.fillStyle=dColors[bg];ctx.fillRect(0,0,640,480)})}"
"function sendDraw(){const t=document.getElementById('tool').value;"
"const f=document.getElementById('fillSel').value;"
"if(t==='text'){const txt=document.getElementById('textInput').value||'Hello';"
"api('text?x='+startX+'&y='+startY+'&text='+encodeURIComponent(txt)+'&size='+"
"document.getElementById('fontSel').value+'&fg='+fg+'&bg='+bg)}"
"else if(t==='pixel'){api('pixel?x='+startX+'&y='+startY+'&color='+fg)}"
"else{api(t+'?x1='+startX+'&y1='+startY+'&x2='+(startX+50)+'&y2='+(startY+50)+\"&color='+fg+'&fill='+f+'&r=25'+' 0 0 1')}}"
"setInterval(()=>{api('status').then(d=>{document.getElementById('status').textContent="
"'Connected: '+d.ip+' | Uptime: '+Math.floor(d.uptime/60)+'m';"
"document.getElementById('info').innerHTML="
"'IP: '+d.ip+'<br>Uptime: '+d.uptime+'s<br>Frames: '+d.frames+'<br>Resolution: '+d.resolution;"
"}).catch(()=>{document.getElementById('status').textContent='Disconnected'})},3000);"
"ctx.fillStyle='#000';ctx.fillRect(0,0,640,480);"
"ctx.fillStyle='#fff';ctx.font='20px monospace';ctx.fillText('Click & drag to draw',200,240);"
"api('status').then(d=>{document.getElementById('status').textContent='Connected: '+d.ip}).catch(()=>{});"
"</script></body></html>";

#endif
